"""Step6 external-boundary regressions with original-source-shaped local inputs."""
from copy import deepcopy
import json

import pytest

from agents.golden_press.external_product_projection import build_external_product_document
from agents.golden_press.external_product_render import _record
from agents.leadgen.press import PressLeadGenReceipt, run_press
from tests.test_native_notice_bridge import graph_fixture, original_fixture, write, NOW


def document(root, context, graph, companion=None):
    return build_external_product_document(market_map={}, graph_payload=graph,
        evidence_pack=json.loads((root / 'pack.json').read_text()), profile={},
        client_name='Testco', slug='testco', as_of=NOW.isoformat(),
        notice_context=context, leadgen=companion)


def companion(context, tier='LEAD_T1'):
    """Full native receipt shape; synthetic tier isolates the consumer boundary.

    This is not a qualifier acceptance test or an authenticated seller lead.
    The source/approval/parent are independently generated by graph_fixture.
    """
    run = context.current_assess_run
    payload = run_press(assess=run).model_dump(mode='json')
    assert payload['leads']
    lead = payload['leads'][0]
    lead.update(lead_tier=tier, readiness='actionable')
    lead['seller_path'].update(kind='channel_reseller', holder='Synthetic holder')
    PressLeadGenReceipt.model_validate(payload)
    return dict(status='complete', assess_run_id=run.run_id,
                assessment={'run': run.model_dump(mode='json')}, receipt=payload)


@pytest.mark.parametrize('tier', ['LEAD_T1', 'LEAD_T2'])
def test_saved_companion_requires_current_source_and_assess(tmp_path, tier):
    context, graph = graph_fixture(tmp_path)
    saved = companion(context, tier)
    before = document(tmp_path, context, graph, saved)
    assert len(before.slots[0].records) == 1
    assert before.slots[4].records[0]['lead_status'] == tier
    path = tmp_path / 'data/cleaned/searches_testco.json'
    sweep = json.loads(path.read_text())
    sweep['results']['sam.gov'][0]['raw_payload']['active'] = 'No'
    write(path, sweep)
    for current in (context, None):
        doc = document(tmp_path, current, graph, saved)
        assert not doc.slots[0].records
        row = doc.slots[4].records[0]
        assert not row['lead_rows'] and not row['targets']
        assert row['saved_lead_rows'][0]['lead_tier'] == tier
        assert row['service_fit'] == row['commercial_route'] == row['window_state'] == 'Unverified'
        assert row['evidence_class'] == 'notice_diagnostic'
        assert row['lead_projection_gaps'] and row['qualification_gaps']
        assert 'Saved lead history' in _record(row, include_targets=True)
    assert saved['receipt']['leads'][0]['lead_tier'] == tier  # input remains immutable


@pytest.mark.parametrize('mutation', ['missing_run', 'wrong_run', 'altered_run', 'wrong_parent', 'wrong_child', 'minimal_receipt'])
def test_source_admission_cannot_authorize_unbound_companion(tmp_path, mutation):
    context, graph = graph_fixture(tmp_path)
    saved = companion(context)
    if mutation == 'missing_run':
        saved.pop('assessment')
    elif mutation == 'wrong_run':
        saved['receipt']['assess_run_id'] = 'other-run'
    elif mutation == 'altered_run':
        saved['assessment']['run']['live']['records'][0]['title'] = 'Changed assessment'
    elif mutation == 'wrong_parent':
        saved['receipt']['parents'][0]['subject_id'] = 'unrelated-subject'
    elif mutation == 'wrong_child':
        saved['receipt']['leads'][0]['assess_run_id'] = 'other-run'
    else:
        saved = dict(status='complete', receipt=dict(client_name='Testco',
            parents=[dict(assessment_id='saved-parent', notice_id='N1')],
            leads=[dict(parent_assessment_id='saved-parent', lead_tier='LEAD_T1')]))
    doc = document(tmp_path, context, graph, saved)
    assert context.accepts_graph(graph)
    assert not doc.slots[0].records
    row = doc.slots[4].records[0]
    assert row['saved_lead_rows'] and not row['lead_rows']
    assert row['lead_projection_gaps']


def test_context_is_rechecked_after_projection(tmp_path, monkeypatch):
    context, graph = graph_fixture(tmp_path)
    saved = companion(context)
    from agents.golden_press import external_product_projection as owner
    normal = owner._priority_records
    def changed_after_priority(*args, **kwargs):
        result = normal(*args, **kwargs)
        path = tmp_path / 'data/cleaned/searches_testco.json'
        sweep = json.loads(path.read_text())
        sweep['results']['sam.gov'][0]['raw_payload']['active'] = 'No'
        write(path, sweep)
        return result
    monkeypatch.setattr(owner, '_priority_records', changed_after_priority)
    doc = document(tmp_path, context, graph, saved)
    assert not doc.slots[0].records
    assert not doc.slots[4].records[0]['lead_rows']
    assert not doc.graph_receipt['current_notice_graph_admitted']


def test_companion_clock_cannot_replace_native_acquisition(tmp_path):
    context, graph = graph_fixture(tmp_path)
    saved = companion(context)
    expected = document(tmp_path, context, graph, saved).slots[4].records[0]['source_as_of']
    saved['evidence_clocks'] = {'N1': dict(source_as_of='2030-01-01T00:00:00Z', status='complete', known=1, total=1)}
    row = document(tmp_path, context, graph, saved).slots[4].records[0]
    assert row['source_as_of'] == expected
    assert row['source_as_of'] != '2030-01-01T00:00:00Z'
    saved['evidence_clocks'] = ['not even a clock mapping']
    row = document(tmp_path, context, graph, saved).slots[4].records[0]
    assert row['source_as_of'] == expected
    row = document(tmp_path, None, graph, saved).slots[4].records[0]
    assert row['source_as_of'] is None
    assert row['source_clock_status'] == 'unverified source acquisition'
    assert 'Source acquisition unavailable' in _record(row)
    assert '<dt>Evidence date</dt>' not in _record(row)


def test_external_contact_fallback_uses_only_bound_original_material(tmp_path):
    context, graph = graph_fixture(tmp_path)
    path = tmp_path / 'pack.json'
    pack = json.loads(path.read_text())
    pack['records'][0].update(contact_name='Unbound Person', contact_email='unsourced@example.invalid')
    write(path, pack)
    row = document(tmp_path, context, graph).slots[4].records[0]
    assert 'unsourced@example.invalid' not in json.dumps(row['targets'])
    # The graph remains accepted: changing a constructor-only contact cannot
    # confer published authority even at this last fallback seam.
    assert context.accepts_graph(graph)


def test_current_original_contact_survives_without_a_constructor_contact(tmp_path):
    def with_contact(sweep):
        sweep['results']['sam.gov'][0]['raw_payload']['pointOfContact'] = [
            dict(type='primary', fullName='Original Official', email='source@example.gov', phone='202-555-0123'),
            dict(type='secondary', fullName='Second Official', email='second@example.gov', phone='202-555-0124')]
    context, graph = graph_fixture(tmp_path, with_contact)
    row = document(tmp_path, context, graph).slots[4].records[0]
    assert 'source@example.gov' in json.dumps(row['targets'])
    assert '202-555-0123' in json.dumps(row['targets'])
    assert 'second@example.gov' in json.dumps(row['targets'])
    assert '202-555-0124' in json.dumps(row['targets'])


def test_nonmatching_closed_representative_and_lineage_are_visible_without_backfill(tmp_path):
    def amended(sweep):
        old = sweep['results']['sam.gov'][0]
        old['raw_payload'].update(solicitation='FULL-CALL-1', office='Office')
        latest = deepcopy(old)
        latest.update(source_id='N2', title='Administrative cancellation', posted_date='2026-07-09',
                      api_url='https://sam.gov/opp/N2/view')
        latest['raw_payload'].update(notice_id='N2', active='No', description_snippet='Administrative cancellation')
        sweep['results']['sam.gov'].append(latest)
        sweep['results']['sam_census']['matched'] = 2
    context, graph = graph_fixture(tmp_path, amended)
    doc = document(tmp_path, context, graph)
    assert not doc.slots[0].records
    assert [r['source_id'] for r in doc.slots[4].records] == ['N1']
    row = doc.slots[4].records[0]
    assert row['current_representative']['source_id'] == 'N2'
    assert row['current_representative']['title'] == 'Administrative cancellation'
    assert row['current_representative']['source_status'] == 'inactive or closed'
    assert row['family_member_ids'] == ['N1', 'N2']
    assert row['family_members'][0]['superseded_by'] == 'N2'
    assert row['response_date'] == '' and row['selected_response_date']
    html = _record(row, include_targets=True)
    assert 'Administrative cancellation' in html and 'https://sam.gov/opp/N2/view' in html
    assert 'inactive or closed' in html and 'Selected notice response (historical)' in html


def test_family_unknown_chronology_and_native_assessment_order_remain_visible(tmp_path):
    def amended(sweep):
        old = sweep['results']['sam.gov'][0]
        old['raw_payload'].update(solicitation='FULL-CALL-1', office='Office')
        other = deepcopy(old)
        other.update(source_id='N2', title='Revised notice', posted_date=None,
                     api_url='https://sam.gov/opp/N2/view')
        other['raw_payload'].update(notice_id='N2')
        sweep['results']['sam.gov'].append(other)
        sweep['results']['sam_census']['matched'] = 2
    context, graph = graph_fixture(tmp_path, amended)
    doc = document(tmp_path, context, graph)
    assert [r['source_id'] for r in doc.slots[4].records] == [r['record_id'] for r in graph['records']]
    assert not doc.slots[0].records
    assert all(r['window_state'] == 'Family chronology unresolved' for r in doc.slots[4].records)
    assert all(r['family_member_ids'] == ['N1', 'N2'] for r in doc.slots[4].records)


def test_current_reviewed_research_survives_without_live_bid_admission(tmp_path):
    from agents.assess import ledger
    from agents.assess.reviewed_cases import save_cases
    from agents.golden_press.notice_bridge import NoticeReadContext
    from agents.golden_press.evidence_pack_v2 import build_corrected_pack
    from agents.golden_press.product_leadgen import restore_assessment_population
    from agents.golden_press.records import EvidencePack
    from tests.test_operating_repair import _book
    from tools.capability import ClientProfile
    sweep = original_fixture(tmp_path)
    review = tmp_path / 'data/review'
    book = _book()
    save_cases(book, review)
    previous = ledger.load_current_assess_run('Testco', 'all', state_dir=tmp_path / 'data/state/assess_runs')
    manifest = ledger.assess_projection_input_manifest('Testco', review_dir=review)
    profile = ClientProfile.model_validate(json.loads((tmp_path / 'clients/testco/profile.json').read_text()))
    requirements = json.loads((review / 'testco.live_requirements.json').read_text())
    run, diagnostics, index = ledger.build_assess_run('Testco', sweep, profile, previous['binding'],
        requirement_reviews_payload=requirements, projection_inputs=manifest, reviewed_cases=book, as_of=NOW)
    ledger.persist_assess_run(run, previous['binding'], diagnostics, index, manifest,
                             state_dir=tmp_path / 'data/state/assess_runs')
    saved = dict(status='complete', assess_run_id=run.run_id, assessment={'run': run.model_dump(mode='json')},
                 receipt=run_press(assess=run, reviewed_cases=book).model_dump(mode='json'))
    pack = restore_assessment_population(EvidencePack(client_name='Testco', generated_at=NOW.isoformat()), saved)
    write(tmp_path / 'pack.json', pack.model_dump(mode='json'))
    context = NoticeReadContext(tmp_path, 'Testco', 'testco', NOW)
    _, graph = build_corrected_pack('testco', 'Testco', root=tmp_path, pressed_pack_path=tmp_path / 'pack.json',
                                   pack_dir=tmp_path / 'output', notice_context=context)
    doc = document(tmp_path, context, graph, saved)
    rows = {r['source_id']: r for r in doc.slots[4].records}
    assert len(rows) == len(run.live.records)
    for case in book.cases:
        row = rows[case.record.notice_id]
        assert row['research'] == case.research.model_dump(mode='json')
        assert row['targets'] == [t.model_dump(mode='json') for t in case.targets]
        assert not row['current_notice_admitted']
    assert len(doc.slots[0].records) == sum(c.research.priority for c in book.cases)
    saved['receipt']['leads'][-1]['research']['next_ask'] = 'Invented new research ask'
    changed = document(tmp_path, context, graph, saved)
    assert len(changed.slots[0].records) == len(doc.slots[0].records) - 1
